### ISSUE TITLE
USER STORY: Store customer support form in the database

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/build_master_shop#27]
As a **site owner** I want to **store customer support form in the database** so that **I can review them**

### Acceptance criteria

- Save form in the database
- Review saved form

### Tasks:

- [x] Save support form data.
- [x] Create a way to view saved forms.
- [x] Test saving and reviewing forms.
