### ISSUE TITLE
USER STORY: Mark requests as "read"

### ISSUE THREAD

**Issue by OleksiiKova** [OleksiiKova/build_master_shop#28]
As a **site owner** I want to **mark user requests as "read"** so that **I can see how many I still need to process**

### Acceptance criteria

- Mark requests as "read"

### Tasks:

- [x] Add functionality to mark requests as "read."
- [x] Update request status in the database.
- [x] Test marking and updating request status.
